name: 04-using-actions
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
        - name: Install dependencies
          run: npm install
        - name: Run Unit tests
          run: npm run test 
        # checkout the code from the repository
        # Install the dependencies for our react application
        # command used - npx create-react-app --template typescript react-app
        #2. Execute automated tests